# Generated by Django 5.2.7 on 2025-12-09 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_bcra', models.CharField(blank=True, max_length=10, verbose_name='Código BCRA')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Código interno (ej: 1.1.0)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
            },
        ),
        migrations.CreateModel(
            name='CuentaFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja Principal, Banco Nación CC$', max_length=100)),
                ('tipo', models.CharField(choices=[('EF', 'Caja / Efectivo'), ('BA', 'Cuenta Bancaria'), ('VI', 'Billetera Virtual (MP, etc)'), ('RE', 'Cuenta Recaudadora (Tarjetas)')], default='EF', max_length=2)),
                ('saldo_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo Actual')),
                ('cbu', models.CharField(blank=True, max_length=22, verbose_name='CBU / CVU')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='Alias CBU')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta de Fondos / Caja',
                'verbose_name_plural': 'Cuentas de Fondos / Cajas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_movimiento', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso'), ('TR', 'Transferencia Interna')], max_length=2)),
                ('monto_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('concepto', models.CharField(help_text='Ej: Cobro Factura F-0001, Pago Luz', max_length=200)),
                ('conciliado', models.BooleanField(default=False, help_text='Marcar si ya figura en el resumen bancario.')),
                ('fecha_conciliacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Fondo',
                'verbose_name_plural': 'Movimientos de Fondos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('requiere_banco', models.BooleanField(default=False, help_text='Pide seleccionar banco (Transferencia).')),
                ('es_cheque', models.BooleanField(default=False, help_text='Habilita la gestión de cheques.')),
                ('es_tarjeta', models.BooleanField(default=False, help_text='Habilita campos de tarjeta (Lote, Cupón).')),
                ('es_retencion', models.BooleanField(default=False, help_text='Para certificados de retención IIBB/Ganancias.')),
            ],
            options={
                'verbose_name': 'Tipo de Valor',
                'verbose_name_plural': 'Tipos de Valores',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(blank=True, default='Transferencia interna de fondos', max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='N° de Transacción Bancaria o Lote', max_length=100)),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('finanzas_aplicadas', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Transferencia Interna / Depósito',
                'verbose_name_plural': 'Transferencias Internas / Depósitos',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('P', 'Propio (Emitido)'), ('T', 'Tercero (Recibido)')], default='T', max_length=1)),
                ('tipo_cheque', models.CharField(choices=[('FIS', 'Físico (Papel)'), ('ECH', 'E-Cheq (Electrónico)')], default='FIS', max_length=3, verbose_name='Formato')),
                ('estado', models.CharField(choices=[('CA', 'En Cartera'), ('DE', 'Depositado (Acred. Pendiente)'), ('CO', 'Cobrado / Acreditado'), ('EN', 'Entregado a Tercero'), ('RE', 'Rechazado'), ('AN', 'Anulado'), ('CU', 'En Custodia (Banco)')], default='CA', max_length=2)),
                ('numero', models.CharField(max_length=50, verbose_name='N° Cheque')),
                ('referencia_bancaria', models.CharField(blank=True, help_text='ID de transacción del E-Cheq', max_length=100, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago / Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuit_librador', models.CharField(blank=True, max_length=11, verbose_name='CUIT Librador')),
                ('nombre_librador', models.CharField(blank=True, max_length=100, verbose_name='Nombre Librador')),
                ('observaciones', models.TextField(blank=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.banco', verbose_name='Banco Emisor')),
            ],
        ),
    ]
