# Generated by Django 5.2.7 on 2025-11-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, help_text='Código interno (ej: 1.1.0)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
            },
        ),
        migrations.AlterModelOptions(
            name='movimientofondo',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Movimiento de Fondo', 'verbose_name_plural': 'Movimientos de Fondos'},
        ),
        migrations.AddField(
            model_name='cheque',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='referencia_bancaria',
            field=models.CharField(blank=True, help_text='ID de transacción del E-Cheq', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='tipo_cheque',
            field=models.CharField(choices=[('FIS', 'Físico (Papel)'), ('ECH', 'E-Cheq (Electrónico)')], default='FIS', max_length=3, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='cuentafondo',
            name='alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias CBU'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='conciliado',
            field=models.BooleanField(default=False, help_text='Marcar si ya figura en el resumen bancario.'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='fecha_conciliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipovalor',
            name='es_retencion',
            field=models.BooleanField(default=False, help_text='Para certificados de retención IIBB/Ganancias.'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='estado',
            field=models.CharField(choices=[('CA', 'En Cartera'), ('DE', 'Depositado (Acred. Pendiente)'), ('CO', 'Cobrado / Acreditado'), ('EN', 'Entregado a Tercero'), ('RE', 'Rechazado'), ('AN', 'Anulado'), ('CU', 'En Custodia (Banco)')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='cuentafondo',
            name='tipo',
            field=models.CharField(choices=[('EF', 'Caja / Efectivo'), ('BA', 'Cuenta Bancaria'), ('VI', 'Billetera Virtual (MP, etc)'), ('RE', 'Cuenta Recaudadora (Tarjetas)')], default='EF', max_length=2),
        ),
        migrations.AlterField(
            model_name='tipovalor',
            name='es_cheque',
            field=models.BooleanField(default=False, help_text='Habilita la gestión de cheques.'),
        ),
        migrations.AlterField(
            model_name='tipovalor',
            name='es_tarjeta',
            field=models.BooleanField(default=False, help_text='Habilita campos de tarjeta (Lote, Cupón).'),
        ),
        migrations.AlterField(
            model_name='tipovalor',
            name='requiere_banco',
            field=models.BooleanField(default=False, help_text='Pide seleccionar banco (Transferencia).'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.centrocosto', verbose_name='Centro de Costo'),
        ),
    ]
