# Generated by Django 5.2.7 on 2026-02-10 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_proveedor_nro_iibb'),
        ('finanzas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('impuesto', models.CharField(choices=[('GAN', 'Ganancias'), ('IIBB', 'Ingresos Brutos'), ('SUSS', 'SUSS / Seguridad Social'), ('IVA', 'IVA')], default='GAN', max_length=4)),
                ('codigo_afip', models.CharField(blank=True, help_text='Código de régimen según AFIP', max_length=10)),
                ('alicuota_inscripto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Inscripto')),
                ('alicuota_no_inscripto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% No Inscripto')),
                ('monto_no_imponible', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo sobre el cual se aplica', max_digits=14)),
                ('monto_minimo_retencion', models.DecimalField(decimal_places=2, default=0, help_text='Si el cálculo da menos que esto, no se retiene', max_digits=14)),
            ],
            options={
                'verbose_name': 'Régimen de Retención',
                'verbose_name_plural': 'Regímenes de Retención',
            },
        ),
        migrations.CreateModel(
            name='CertificadoRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero', models.CharField(max_length=50, verbose_name='N° Certificado')),
                ('base_calculo', models.DecimalField(decimal_places=2, help_text='Monto sujeto a retención', max_digits=14)),
                ('importe_retenido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('token_validacion', models.CharField(blank=True, editable=False, max_length=64)),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_emitidos', to='compras.ordenpago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.regimenretencion')),
            ],
            options={
                'verbose_name': 'Certificado de Retención',
                'verbose_name_plural': 'Certificados de Retención',
            },
        ),
    ]
