# Generated by Django 5.2.7 on 2026-02-18 00:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_tarjeta_cupontarjeta_movimientofondo_cupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupontarjeta',
            name='liquidacion_banco',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text="Cuenta donde se acreditan provisoriamente los cupones (Ej: 'Visa a Cobrar').", limit_choices_to={'tipo': 'RE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_asociadas', to='finanzas.cuentafondo'),
        ),
        migrations.AlterField(
            model_name='cupontarjeta',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente de Presentación'), ('PR', 'Presentado (Cierre Lote)'), ('LI', 'Liquidado / En Banco'), ('RE', 'Rechazado / Contracargo')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='movimientofondo',
            name='tipo_valor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor'),
        ),
        migrations.CreateModel(
            name='LiquidacionTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_liquidacion', models.DateField(default=django.utils.timezone.now)),
                ('numero_liquidacion', models.CharField(max_length=50, verbose_name='N° Liquidación')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, help_text='Suma de cupones', max_digits=14)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, help_text='Comisiones + Impuestos', max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, help_text='Lo que realmente entró al banco', max_digits=14)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_iibb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_ganancias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('procesada', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cuenta_banco', models.ForeignKey(limit_choices_to={'tipo': 'BA'}, on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentafondo', verbose_name='Banco Destino')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='cupontarjeta',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_asociados', to='finanzas.liquidaciontarjeta'),
        ),
        migrations.CreateModel(
            name='PlanTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Ahora 3, Cuota Simple', max_length=100)),
                ('cuotas', models.PositiveIntegerField(default=1)),
                ('coeficiente', models.DecimalField(decimal_places=4, default=1.0, help_text='1.00 = Sin interés. 1.15 = 15% recargo.', max_digits=6)),
                ('tna', models.DecimalField(decimal_places=2, default=0, help_text='Solo informativo', max_digits=6, verbose_name='TNA %')),
                ('activo', models.BooleanField(default=True)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='finanzas.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='cupontarjeta',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.plantarjeta'),
        ),
    ]
