# Generated by Django 5.2.7 on 2026-02-25 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_cuentafondo_tipo_alter_cupontarjeta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoretencion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='cupontarjeta',
            name='fecha_operacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Operación'),
        ),
        migrations.AlterField(
            model_name='movimientofondo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='transferenciainterna',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
    ]
