# Generated by Django 5.2.7 on 2026-06-12 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_remove_centrocosto_activo_remove_cuentafondo_activa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='centrocosto',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='centrocosto',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='certificadoretencion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='certificadoretencion',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='cuentafondo',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='cupontarjeta',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='liquidaciontarjeta',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='plantarjeta',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='regimenretencion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='banco',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='banco',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='certificadoretencion',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='certificadoretencion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cuentafondo',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cupontarjeta',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='liquidaciontarjeta',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='plantarjeta',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='regimenretencion',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
