# Generated by Django 5.2.7 on 2025-10-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si este es el depósito principal o por defecto.')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('cod_articulo', models.CharField(blank=True, help_text='Dejar en blanco para generar un código automático.', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código de Artículo')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13, null=True, verbose_name='Código de Barras (EAN)')),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código QR')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('perfil', models.CharField(choices=[('CV', 'Compra/Venta'), ('CO', 'Compra'), ('VE', 'Venta')], default='CV', max_length=2, verbose_name='Perfil del Artículo')),
                ('unidad_medida', models.CharField(choices=[('UN', 'Unidades'), ('KG', 'Kilogramo'), ('LT', 'Litro'), ('MT', 'Metro')], default='UN', max_length=2, verbose_name='Unidad de Medida')),
                ('precio_costo_original', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Original')),
                ('precio_venta_original', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Venta Original')),
                ('utilidad', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de ganancia sobre el costo en moneda base.', max_digits=5, verbose_name='Utilidad (%)')),
                ('precio_costo_base', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Costo en Moneda Base')),
                ('precio_venta_base', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Venta en Moneda Base')),
                ('administra_stock', models.BooleanField(default=True, verbose_name='¿Administra Stock?')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Máximo')),
                ('punto_pedido', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Punto de Pedido')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota Interna')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.impuesto', verbose_name='Impuesto (IVA)')),
                ('moneda_costo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_costo', to='parametros.moneda', verbose_name='Moneda de Costo')),
                ('moneda_venta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta', to='parametros.moneda', verbose_name='Moneda de Venta')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca', verbose_name='Marca')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.rubro', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='StockArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.articulo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.deposito')),
            ],
            options={
                'verbose_name': 'Stock por Depósito',
                'verbose_name_plural': 'Stocks por Depósito',
                'unique_together': {('articulo', 'deposito')},
            },
        ),
    ]
