# Generated by Django 5.2.7 on 2025-10-14 01:59

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0004_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='impuesto',
            field=models.ForeignKey(blank=True, help_text='El impuesto principal que se aplica al precio de venta.', null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.reglaimpuesto', verbose_name='Regla Impositiva'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida_stock',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, help_text='La unidad en la que se controla el inventario (la más pequeña).', on_delete=django.db.models.deletion.PROTECT, to='parametros.unidadmedida', verbose_name='Unidad de Medida de Stock'),
        ),
        migrations.AddField(
            model_name='conversionunidadmedida',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_uom', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='conversionunidadmedida',
            name='unidad_externa',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, help_text='Unidad a convertir (ej: Caja, Botella, Bulto)', on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_externas', to='parametros.unidadmedida'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='proveedorarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='proveedorarticulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='articulos_directos', through='inventario.ProveedorArticulo', to='compras.proveedor', verbose_name='Proveedores Relacionados'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.rubro', verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.deposito'),
        ),
        migrations.AlterUniqueTogether(
            name='conversionunidadmedida',
            unique_together={('articulo', 'unidad_externa')},
        ),
        migrations.AddConstraint(
            model_name='proveedorarticulo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_fuente_de_verdad', True)), fields=('articulo',), name='unique_fuente_de_verdad_por_articulo'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedorarticulo',
            unique_together={('proveedor', 'articulo')},
        ),
        migrations.AlterUniqueTogether(
            name='stockarticulo',
            unique_together={('articulo', 'deposito')},
        ),
    ]
