# Generated by Django 5.2.7 on 2025-10-11 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.impuesto', verbose_name='Impuesto (IVA)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.rubro', verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.deposito'),
        ),
        migrations.AlterUniqueTogether(
            name='stockarticulo',
            unique_together={('articulo', 'deposito')},
        ),
    ]
