# Generated by Django 5.2.7 on 2025-12-09 23:26

import django.db.models.deletion
import parametros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0004_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria_impositiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.categoriaimpositiva', verbose_name='Categoría Impositiva'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo_unidades',
            field=models.ForeignKey(blank=True, help_text='Define la categoría de unidades del artículo (Peso, Volumen, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.grupounidadmedida', verbose_name='Grupo de Unidades'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='impuestos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione todos los impuestos que aplican a este artículo (IVA, Internos, etc.)', to='parametros.impuesto', verbose_name='Impuestos Aplicables'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_costo_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_costo', to='parametros.moneda', verbose_name='Moneda de Costo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta_moneda', to='parametros.moneda', verbose_name='Moneda de Venta'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida_stock',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_stock', to='parametros.unidadmedida', verbose_name='U.M. de Stock'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida_venta',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta', to='parametros.unidadmedida', verbose_name='U.M. de Venta'),
        ),
        migrations.AddField(
            model_name='conversionunidadmedida',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_uom', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='conversionunidadmedida',
            name='unidad_externa',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, help_text='Unidad a convertir (ej: Caja, Botella, Bulto)', on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_externas', to='parametros.unidadmedida'),
        ),
        migrations.AddField(
            model_name='itemmovimientostock',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='deposito_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.deposito', verbose_name='Depósito Destino (Entra aquí)'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='deposito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.deposito', verbose_name='Depósito Origen (Sale de aquí)'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='serie',
            field=models.ForeignKey(help_text="Ej: 'Ajuste Inventario', 'Transferencia Sucursal 1'", on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Concepto'),
        ),
        migrations.AddField(
            model_name='itemmovimientostock',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.movimientostock'),
        ),
        migrations.AddField(
            model_name='proveedorarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='proveedorarticulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='articulos_directos', through='inventario.ProveedorArticulo', to='compras.proveedor', verbose_name='Proveedores Relacionados'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.rubro', verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.deposito'),
        ),
        migrations.AlterUniqueTogether(
            name='conversionunidadmedida',
            unique_together={('articulo', 'unidad_externa')},
        ),
        migrations.AddConstraint(
            model_name='proveedorarticulo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_fuente_de_verdad', True)), fields=('articulo',), name='unique_fuente_de_verdad_por_articulo'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedorarticulo',
            unique_together={('proveedor', 'articulo')},
        ),
        migrations.AlterUniqueTogether(
            name='stockarticulo',
            unique_together={('articulo', 'deposito')},
        ),
    ]
