# Generated by Django 5.2.7 on 2025-11-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='impuesto',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_costo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_costo_currency',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_venta_currency',
        ),
    ]
