# Generated by Django 5.2.7 on 2026-01-14 16:54

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_tipostock_alter_historicomovimientos_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicomovimientos',
            options={'verbose_name': 'Histórico Legacy (DEPRECADO)', 'verbose_name_plural': 'Historial Legacy (DEPRECADO)'},
        ),
        migrations.RemoveIndex(
            model_name='movimientostockledger',
            name='inventario__articul_8c04f1_idx',
        ),
        migrations.AddField(
            model_name='tipostock',
            name='afecta_valorizacion',
            field=models.BooleanField(default=True, help_text='¿Impacta en la valorización del inventario?'),
        ),
        migrations.AddField(
            model_name='tipostock',
            name='es_de_terceros',
            field=models.BooleanField(default=False, help_text='Mercadería en consignación.'),
        ),
        migrations.AddField(
            model_name='tipostock',
            name='es_en_transito',
            field=models.BooleanField(default=False, help_text='Mercadería viajando entre ubicaciones.'),
        ),
        migrations.AlterField(
            model_name='movimientostockledger',
            name='fecha_movimiento',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha Efectiva'),
        ),
        migrations.AddIndex(
            model_name='movimientostockledger',
            index=models.Index(fields=['articulo', 'tipo_stock', 'fecha_movimiento'], name='inventario__articul_dbcbae_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostockledger',
            index=models.Index(fields=['origen_sistema', 'origen_referencia'], name='inventario__origen__dae569_idx'),
        ),
    ]
