# Generated by Django 5.2.7 on 2026-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_historicomovimientos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='permite_stock_negativo',
            field=models.BooleanField(default=False, help_text='Define si este artículo específico puede quedar en saldo negativo.', verbose_name='¿Permite Stock Negativo?'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='permite_stock_negativo',
            field=models.BooleanField(default=False, help_text='Si está marcado, este depósito permite egresos sin stock suficiente, salvo override manual.', verbose_name='¿Permite Stock Negativo?'),
        ),
    ]
