# Generated by Django 5.2.7 on 2025-12-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_movimientostock_stock_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto'),
        ),
    ]
