# Generated by Django 5.2.7 on 2026-01-15 17:50

from django.db import migrations

def seed_tipos_stock(apps, schema_editor):
    TipoStock = apps.get_model('inventario', 'TipoStock')

    # 1. REAL (Físico y Vendible)
    TipoStock.objects.update_or_create(
        codigo='REAL',
        defaults={
            'nombre': 'Stock Físico Real',
            'es_fisico': True, 'es_vendible': True, 'es_reservado': False,
            'es_en_transito': False, 'es_de_terceros': False, 'afecta_valorizacion': True
        }
    )

    # 2. RSRV (Comprometido)
    TipoStock.objects.update_or_create(
        codigo='RSRV',
        defaults={
            'nombre': 'Stock Comprometido',
            'es_fisico': False, 'es_vendible': False, 'es_reservado': True,
            'es_en_transito': False, 'es_de_terceros': False, 'afecta_valorizacion': False
        }
    )

    # 3. RCPT (A Recibir - Orden de Compra Pendiente)
    TipoStock.objects.update_or_create(
        codigo='RCPT',
        defaults={
            'nombre': 'A Recibir (Orden de Compra)',
            'es_fisico': False, 'es_vendible': False, 'es_reservado': False,
            'es_en_transito': False, 'es_de_terceros': False, 'afecta_valorizacion': False
        }
    )

    # 4. TRNS (En Tránsito entre depósitos)
    TipoStock.objects.update_or_create(
        codigo='TRNS',
        defaults={
            'nombre': 'En Tránsito (Transferencia)',
            'es_fisico': False, 'es_vendible': False, 'es_reservado': False,
            'es_en_transito': True, 'es_de_terceros': False, 'afecta_valorizacion': True
        }
    )

    # 5. QC (Control de Calidad / Cuarentena)
    TipoStock.objects.update_or_create(
        codigo='QC',
        defaults={
            'nombre': 'Control de Calidad / Bloqueado',
            'es_fisico': True, 'es_vendible': False, 'es_reservado': False,  # Ocupa lugar pero no se vende
            'es_en_transito': False, 'es_de_terceros': False, 'afecta_valorizacion': True
        }
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    # ¡¡¡NO BORRES NI MODIFIQUES LA LÍNEA 'dependencies' QUE YA ESTÁ AQUÍ!!!
    # Django la generó automáticamente apuntando a la migración anterior correcta.
    dependencies = [
        ('inventario', '0006_articulo_permite_stock_negativo_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_tipos_stock, reverse_func),
    ]




