# Generated by Django 5.2.7 on 2026-01-17 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_transferenciainterna_itemtransferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo de Ajuste',
                'verbose_name_plural': 'Motivos de Ajuste',
            },
        ),
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('stock_aplicado', models.BooleanField(default=False, editable=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito', verbose_name='Depósito')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.motivoajuste')),
            ],
            options={
                'verbose_name': 'Ajuste Manual de Stock',
                'verbose_name_plural': 'Ajustes Manuales de Stock',
            },
        ),
        migrations.CreateModel(
            name='ItemAjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('E', 'Entrada (+ Suma Stock)'), ('S', 'Salida (- Resta Stock)')], default='S', max_length=1)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Ingrese siempre valor positivo.', max_digits=10)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ajustestock')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo')),
            ],
        ),
    ]
