# Generated by Django 5.2.7 on 2026-06-12 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_articulo_alto_cm_articulo_ancho_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustestock',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='transferenciainterna',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articulo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_inventario', to=settings.AUTH_USER_MODEL),
        ),
    ]
