# Generated by Django 5.2.7 on 2025-10-08 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entidades.entidad')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Dejar en blanco para generar un código automático.', max_length=50, null=True, unique=True, verbose_name='Código de Proveedor')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Fantasía')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(editable=False, max_length=1)),
                ('punto_venta', models.PositiveIntegerField(default=1, verbose_name='Punto de Venta')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha del Comprobante')),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('FN', 'Finalizado'), ('AN', 'Anulado')], default='BR', max_length=2, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('comprobante_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_derivados', to='compras.comprobantecompra')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Comprobante de Compra',
                'verbose_name_plural': 'Comprobantes de Compra',
                'unique_together': {('tipo_comprobante', 'punto_venta', 'numero', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='ComprobanteCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_costo_unitario_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo', verbose_name='Artículo')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.comprobantecompra')),
                ('moneda_costo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda', verbose_name='Moneda de Costo')),
            ],
        ),
    ]
