# Generated by Django 5.2.7 on 2025-10-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entidades.entidad')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Dejar en blanco para generar código automático.', max_length=50, null=True, unique=True, verbose_name='Código de Proveedor')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Fantasía')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='comprobante_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_derivados', to='compras.comprobantecompra'),
        ),
    ]
