# Generated by Django 5.2.7 on 2025-10-17 11:17

import compras.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.comprobantecompra'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='precio_costo_unitario_moneda',
            field=models.ForeignKey(default=compras.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda'),
        ),
        migrations.AddField(
            model_name='historialprecioproveedor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlistapreciosproveedor',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_proveedor', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='itemlistapreciosproveedor',
            name='precio_lista_moneda',
            field=models.ForeignKey(default=compras.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='itemlistapreciosproveedor',
            name='unidad_medida_compra',
            field=models.ForeignKey(help_text='En qué unidad el proveedor vende este artículo', on_delete=django.db.models.deletion.PROTECT, to='parametros.unidadmedida', verbose_name='Unidad de Medida de Compra'),
        ),
        migrations.AddField(
            model_name='historialprecioproveedor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='compras.itemlistapreciosproveedor'),
        ),
        migrations.AddField(
            model_name='itemlistapreciosproveedor',
            name='lista_precios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.listapreciosproveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles que pueden gestionar este proveedor.', to='parametros.role'),
        ),
        migrations.AddField(
            model_name='listapreciosproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlistapreciosproveedor',
            unique_together={('lista_precios', 'articulo', 'cantidad_minima')},
        ),
        migrations.AlterUniqueTogether(
            name='listapreciosproveedor',
            unique_together={('proveedor', 'nombre')},
        ),
    ]
