# Generated by Django 5.2.7 on 2025-10-11 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.comprobantecompra'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles que tienen permiso para gestionar este proveedor.', to='parametros.role'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='comprobantecompra',
            unique_together={('tipo_comprobante', 'punto_venta', 'numero', 'proveedor')},
        ),
    ]
