# Generated by Django 5.2.7 on 2026-01-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpagovalor',
            name='es_echeq',
            field=models.BooleanField(default=False, help_text='Marcar si es cheque electrónico', verbose_name='¿Es E-Cheq?'),
        ),
    ]
