# Generated by Django 5.2.7 on 2025-11-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_comprobantecompra_fecha_and_more'),
        ('parametros', '0003_seriedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Usar solo para comprobantes propios (Orden de Compra, Devolución). Para facturas de proveedor, dejar vacío.', null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie (Opcional)'),
        ),
    ]
