# Generated by Django 5.2.7 on 2026-02-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_proveedor_nro_iibb'),
        ('finanzas', '0003_regimenretencion_certificadoretencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='regimen_ganancias',
            field=models.ForeignKey(blank=True, limit_choices_to={'impuesto': 'GAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_ganancias', to='finanzas.regimenretencion', verbose_name='Régimen Ganancias (Default)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regimen_iibb',
            field=models.ForeignKey(blank=True, limit_choices_to={'impuesto': 'IIBB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_iibb', to='finanzas.regimenretencion', verbose_name='Régimen IIBB (Default)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='situacion_iibb',
            field=models.CharField(blank=True, max_length=30, verbose_name='Situación IIBB (Convenio/Local)'),
        ),
    ]
