# Generated by Django 5.2.7 on 2025-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_comprobantecompra_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='stock_aplicado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='estado',
            field=models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2, verbose_name='Estado'),
        ),
    ]
