# Generated by Django 5.2.7 on 2025-10-17 11:17

import django.db.models.deletion
import parametros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre clave del contador, ej: 'codigo_articulo'", max_length=100, unique=True)),
                ('prefijo', models.CharField(default='P', help_text="Prefijo para el código, ej: 'P'", max_length=5)),
                ('ultimo_valor', models.PositiveIntegerField(default=0, verbose_name='Último Valor Utilizado')),
            ],
            options={
                'verbose_name': 'Contador del Sistema',
                'verbose_name_plural': 'Contadores del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('cotizacion', models.DecimalField(decimal_places=2, help_text='Cotización respecto a la moneda base.', max_digits=10, verbose_name='Cotización')),
                ('es_base', models.BooleanField(default=False, help_text='Marcar si esta es la moneda base del sistema.', verbose_name='¿Es Moneda Base?')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('por_defecto', models.BooleanField(default=False, verbose_name='¿Es el país por defecto?')),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Comprobante')),
                ('codigo_afip', models.CharField(blank=True, help_text='Código de AFIP si corresponde', max_length=3, null=True)),
                ('letra', models.CharField(max_length=1)),
                ('afecta_stock', models.BooleanField(default=False, help_text='Marcar si este comprobante modifica el stock.')),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobante',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(default=parametros.models.get_default_pais, on_delete=django.db.models.deletion.PROTECT, to='parametros.pais')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'unique_together': {('nombre', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del rol, ej: Vendedor', max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permisos generales asignados.', to='auth.permission')),
                ('users', models.ManyToManyField(blank=True, help_text='Usuarios con este rol.', related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='ReglaImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'IVA 21% General'", max_length=100, verbose_name='Nombre de la Regla')),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa/Alícuota')),
                ('tipo_impuesto', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], default='porcentaje', max_length=20, verbose_name='Tipo de Cálculo')),
                ('aplica_a', models.CharField(choices=[('venta', 'Ventas'), ('compra', 'Compras')], default='venta', max_length=50, verbose_name='Aplica a')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activa?')),
                ('valido_desde', models.DateField(verbose_name='Válido Desde')),
                ('valido_hasta', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('categorias_producto', models.ManyToManyField(blank=True, help_text='Dejar en blanco para que aplique a todas.', to='inventario.rubro', verbose_name='Categorías de Producto (Rubros)')),
                ('tipos_comprobante', models.ManyToManyField(blank=True, help_text='Dejar en blanco para que aplique a todos.', to='parametros.tipocomprobante', verbose_name='Tipos de Comprobante')),
            ],
            options={
                'verbose_name': 'Regla de Impuesto',
                'verbose_name_plural': 'Reglas de Impuesto',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('codigo_area_telefonico', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Área')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.provincia')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'unique_together': {('nombre', 'provincia')},
            },
        ),
    ]
