# Generated by Django 5.2.7 on 2025-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'Tipos de Comprobante'},
        ),
        migrations.RemoveField(
            model_name='tipocomprobante',
            name='afecta_stock',
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='clase',
            field=models.CharField(choices=[('V', 'Ventas (Cliente)'), ('C', 'Compras (Proveedor)'), ('F', 'Fondos / Caja'), ('S', 'Stock Interno')], default='V', max_length=1, verbose_name='Clase de Comprobante'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='es_fiscal',
            field=models.BooleanField(default=False, help_text='Requiere validación AFIP', verbose_name='¿Es Fiscal?'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='mueve_caja',
            field=models.BooleanField(default=False, help_text='Si mueve dinero real inmediatamente (ej: Recibo, Ticket Contado)', verbose_name='¿Mueve Caja?'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='mueve_cta_cte',
            field=models.BooleanField(default=True, help_text='Si afecta el saldo del cliente/proveedor (Deuda/Crédito)', verbose_name='¿Afecta Cta. Cte?'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='mueve_stock',
            field=models.BooleanField(default=False, verbose_name='¿Mueve Stock?'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='numeracion_automatica',
            field=models.BooleanField(default=True, help_text='Si el sistema asigna el número (False para facturas de proveedores)'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='signo_stock',
            field=models.IntegerField(choices=[(1, 'Suma Stock (+)'), (-1, 'Resta Stock (-)'), (0, 'No Mueve Stock')], default=0, help_text='Ej: Venta resta (-1), Compra suma (+1), Presupuesto (0)', verbose_name='Sentido del Stock'),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='letra',
            field=models.CharField(blank=True, help_text='A, B, C, X, R...', max_length=1, null=True),
        ),
    ]
