# Generated by Django 5.2.7 on 2025-11-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_articulo_categoria_impositiva_articulo_ean_and_more'),
        ('parametros', '0002_categoriaimpositiva_grupounidadmedida_impuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Facturación Electrónica Sucursal Centro', max_length=100, verbose_name='Nombre de la Serie')),
                ('punto_venta', models.PositiveIntegerField(default=1, verbose_name='Punto de Venta (AFIP)')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último Número Usado')),
                ('es_manual', models.BooleanField(default=False, help_text='Si se marca, el usuario debe escribir el número (ej: facturas viejas). Si no, es automático.', verbose_name='¿Es numeración manual?')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('deposito_defecto', models.ForeignKey(blank=True, help_text='Si se define, los movimientos de stock afectarán a este depósito automáticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.deposito', verbose_name='Depósito por Defecto')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante Legal')),
            ],
            options={
                'verbose_name': 'Serie de Documento (Talonario)',
                'verbose_name_plural': 'Series de Documentos (Talonarios)',
                'unique_together': {('tipo_comprobante', 'punto_venta')},
            },
        ),
    ]
