# Generated by Django 5.2.7 on 2025-12-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_alter_tipocomprobante_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfipCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Certificado Producción 2024', max_length=100)),
                ('certificado', models.FileField(upload_to='afip/certs/', verbose_name='Certificado (.crt)')),
                ('clave_privada', models.FileField(upload_to='afip/keys/', verbose_name='Clave Privada (.key)')),
                ('cuit', models.CharField(help_text='CUIT de la empresa emisora (sin guiones)', max_length=11)),
                ('es_produccion', models.BooleanField(default=False, help_text='Si está marcado, emitirá facturas REALES con validez fiscal. Si no, usa servidores de prueba.', verbose_name='¿Es Producción?')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certificado AFIP',
                'verbose_name_plural': 'Certificados AFIP',
            },
        ),
        migrations.CreateModel(
            name='AfipToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Ej: wsfe', max_length=10)),
                ('unique_id', models.CharField(help_text='Identificador único del request', max_length=100)),
                ('token', models.TextField()),
                ('sign', models.TextField()),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('expira', models.DateTimeField(help_text='Fecha de expiración informada por AFIP')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.afipcertificado')),
            ],
        ),
    ]
