# Generated by Django 5.2.7 on 2025-12-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_initial'),
        ('parametros', '0003_seriedocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresa/')),
                ('nombre_fantasia', models.CharField(help_text='Nombre comercial para el ticket', max_length=200)),
                ('inicio_actividades', models.DateField(verbose_name='Inicio de Actividades')),
                ('ingresos_brutos', models.CharField(max_length=50, verbose_name='N° Ingresos Brutos')),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='entidades.entidad', verbose_name='Entidad Fiscal')),
                ('moneda_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_principal', to='parametros.moneda')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
