# Generated by Django 5.2.7 on 2025-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_alter_afipcertificado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afipcertificado',
            name='vencimiento',
            field=models.DateField(blank=True, help_text='Fecha en la que expira el certificado (verifique el archivo .crt)', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
