# Generated by Django 5.2.7 on 2025-12-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_configuracionsmtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriedocumento',
            name='solicitar_cae_automaticamente',
            field=models.BooleanField(default=False, help_text='Si se activa, el sistema intentará conectar con AFIP inmediatamente al confirmar la venta. Si falla, quedará pendiente.', verbose_name='Solicitar CAE Automático'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='tipo_stock_afectado',
            field=models.CharField(choices=[('R', 'Stock Físico (Real) - Ej: Factura, Remito'), ('C', 'Stock Comprometido (Reserva) - Ej: Nota de Pedido'), ('N', 'No Afecta Stock - Ej: Presupuesto informativo')], default='R', help_text='Define si el comprobante afecta el inventario físico real o solo genera un compromiso/reserva.', max_length=1, verbose_name='Tipo de Stock Afectado'),
        ),
        migrations.AlterField(
            model_name='seriedocumento',
            name='es_manual',
            field=models.BooleanField(default=False, help_text='Si se marca, el usuario escribe el número (factureros papel). Si no, el sistema numera y/o pide CAE.', verbose_name='¿Es numeración manual?'),
        ),
    ]
