# Generated by Django 5.2.7 on 2026-06-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0015_reglaconversioncomprobante_confirmar_automaticamente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglaconversioncomprobante',
            name='copia_items',
            field=models.BooleanField(default=True, help_text='Si está activo, los ítems del comprobante origen se copian al nuevo.', verbose_name='Copiar ítems'),
        ),
        migrations.AlterField(
            model_name='reglaconversioncomprobante',
            name='etiqueta',
            field=models.CharField(blank=True, help_text='Ej: "Convertir a Factura". Si se deja vacío se genera automáticamente.', max_length=60, verbose_name='Etiqueta del botón'),
        ),
        migrations.AlterField(
            model_name='reglaconversioncomprobante',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden de aparición'),
        ),
    ]
