# Generated by Django 5.2.7 on 2026-06-12 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0016_alter_reglaconversioncomprobante_copia_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seriedocumento',
            name='usuarios_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Seleccione qué usuarios pueden facturar usando este talonario.', related_name='series_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Autorizados'),
        ),
    ]
