# Generated by Django 5.2.7 on 2026-06-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0017_seriedocumento_usuarios_autorizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargamasiva',
            name='entidad',
            field=models.CharField(choices=[('ARTICULOS', 'Artículos / Inventario'), ('STOCK_INICIAL', 'Saldos Iniciales de Stock'), ('PRECIOS_VENTA', 'Listas de Precios (Venta)'), ('PRECIOS_COMPRA', 'Listas de Precios (Compra)'), ('CLIENTES', 'Clientes'), ('PROVEEDORES', 'Proveedores')], max_length=50, verbose_name='Entidad a Importar'),
        ),
    ]
