# Generated by Django 5.2.7 on 2025-12-16 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_situacioniva_codigo_afip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidademail',
            options={'verbose_name': 'Email Adicional', 'verbose_name_plural': 'Emails Adicionales'},
        ),
        migrations.RemoveField(
            model_name='entidaddomicilio',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='entidad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Facturación'),
        ),
        migrations.AddField(
            model_name='entidaddomicilio',
            name='calle',
            field=models.CharField(default='-', max_length=200, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidaddomicilio',
            name='dpto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Depto'),
        ),
        migrations.AddField(
            model_name='entidaddomicilio',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='entidaddomicilio',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entidademail',
            name='tipo',
            field=models.CharField(default='Secundario', help_text='Ej: Administración, Compras', max_length=50),
        ),
        migrations.AlterField(
            model_name='entidademail',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_secundarios', to='entidades.entidad'),
        ),
    ]
