# Generated by Django 5.2.7 on 2025-10-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_pricelist_cliente_price_list_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='formula',
            field=models.CharField(blank=True, help_text="Ej: 'costo * 1.5 + 50'. Usa 'costo' como variable. Se aplica si no hay precio específico.", max_length=255, verbose_name='Fórmula de Precio Personalizada'),
        ),
    ]
