# Generated by Django 5.2.7 on 2025-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_comprobanteventa_afip_error_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='afip_error',
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='afip_observaciones',
            field=models.TextField(blank=True, help_text='Mensajes de AFIP (Observaciones o Errores)', null=True),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='afip_resultado',
            field=models.CharField(blank=True, help_text='A: Aprobado, R: Rechazado, P: Parcial', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='cae',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CAE'),
        ),
    ]
