# Generated by Django 5.2.7 on 2025-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_comprobanteventa_afip_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='afip_error',
            field=models.TextField(blank=True, null=True, verbose_name='Error AFIP'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='afip_observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='afip_resultado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
