# Generated by Django 5.2.7 on 2025-11-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_seriedocumento'),
        ('ventas', '0004_alter_comprobanteventa_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='tipo_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante'),
        ),
    ]
