# Generated by Django 5.2.7 on 2025-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_comprobantependientecae'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoImpresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Diseño')),
                ('archivo_template', models.CharField(help_text='Ej: ventas/pdf/factura_moderna.html', max_length=100, verbose_name='Ruta del Template HTML')),
            ],
            options={
                'verbose_name': 'Diseño de Impresión',
                'verbose_name_plural': 'Diseños de Impresión',
            },
        ),
    ]
