# Generated by Django 5.2.7 on 2025-11-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_comprobanteventa_saldo_pendiente_recibo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='permite_cta_cte',
            field=models.BooleanField(default=False, help_text='Si está desactivado, este cliente solo puede operar de CONTADO.', verbose_name='Habilitar Cuenta Corriente'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='condicion_venta',
            field=models.CharField(choices=[('CO', 'Contado'), ('CC', 'Cuenta Corriente')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='estado',
            field=models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='impuestos',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='punto_venta',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
