# Generated by Django 5.2.7 on 2025-12-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_disenoimpresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenoimpresion',
            name='contenido_html',
            field=models.TextField(blank=True, help_text='Si pegas código aquí, el sistema lo usará PRIORITARIAMENTE sobre el archivo físico.', null=True, verbose_name='Código HTML (Base de Datos)'),
        ),
        migrations.AlterField(
            model_name='disenoimpresion',
            name='archivo_template',
            field=models.CharField(default='ventas/pdf/factura_premium.html', help_text='Ej: ventas/pdf/factura_premium.html', max_length=100, verbose_name='Ruta del Template HTML'),
        ),
    ]
