# Generated by Django 5.2.7 on 2025-12-06 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_transferenciainterna'),
        ('inventario', '0006_movimientostock_stock_aplicado_and_more'),
        ('parametros', '0003_seriedocumento'),
        ('ventas', '0009_alter_recibo_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['min_quantity']},
        ),
        migrations.AddField(
            model_name='recibo',
            name='origen',
            field=models.CharField(choices=[('CTA', 'Cobranza Cuenta Corriente'), ('CON', 'Venta Contado')], default='CTA', max_length=3, verbose_name='Origen de Fondos'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Talonario'),
        ),
        migrations.AlterField(
            model_name='comprobanteventaitem',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo'),
        ),
        migrations.AlterField(
            model_name='comprobanteventaitem',
            name='precio_unitario_original',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='formula',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_monto',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciboimputacion',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.comprobanteventa'),
        ),
        migrations.AlterField(
            model_name='reciboimputacion',
            name='monto_imputado',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='recibovalor',
            name='banco_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.banco'),
        ),
        migrations.AlterField(
            model_name='recibovalor',
            name='cheque_tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cheque'),
        ),
        migrations.AlterField(
            model_name='recibovalor',
            name='cuit_librador',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='recibovalor',
            name='fecha_cobro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recibovalor',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
