# Generated by Django 5.2.7 on 2026-02-17 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_tarjeta_cupontarjeta_movimientofondo_cupon'),
        ('ventas', '0012_remove_comprobanteventa_comprobante_asociado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCobroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.CharField(blank=True, help_text='N° Cheque, Banco, o detalles', max_length=100)),
                ('tarjeta_lote', models.CharField(blank=True, max_length=20)),
                ('tarjeta_cupon', models.CharField(blank=True, max_length=50)),
                ('tarjeta_cuotas', models.IntegerField(blank=True, default=1)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_asociados', to='ventas.comprobanteventa')),
                ('destino', models.ForeignKey(limit_choices_to={'activa': True}, on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentafondo')),
                ('tarjeta_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.tarjeta')),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor')),
            ],
        ),
    ]
