# Generated by Django 5.2.7 on 2026-02-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_comprobantecobroitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibovalor',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Detalle: N° Cheque, Banco, Lote Tarjeta, etc.', max_length=150),
        ),
    ]
