# Generated by Django 5.2.7 on 2026-02-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_remove_plantarjeta_coeficiente_and_more'),
        ('ventas', '0014_recibovalor_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecobroitem',
            name='tarjeta_cuotas',
        ),
        migrations.RemoveField(
            model_name='comprobantecobroitem',
            name='tarjeta_marca',
        ),
        migrations.AddField(
            model_name='comprobantecobroitem',
            name='tarjeta_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.plantarjeta', verbose_name='Plan Tarjeta'),
        ),
    ]
