# Generated by Django 5.2.7 on 2026-02-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_remove_comprobantecobroitem_tarjeta_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecobroitem',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Detalle opcional', max_length=100),
        ),
        migrations.AlterField(
            model_name='comprobantecobroitem',
            name='tarjeta_cupon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cupón'),
        ),
        migrations.AlterField(
            model_name='comprobantecobroitem',
            name='tarjeta_lote',
            field=models.CharField(blank=True, max_length=20, verbose_name='Lote'),
        ),
    ]
