# Generated by Django 5.2.7 on 2026-03-16 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_alter_comprobanteventa_letra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('MIN', 'Minorista'), ('MAY', 'Mayorista'), ('VIP', 'VIP / Premium'), ('GOB', 'Gobierno / Institución'), ('EXP', 'Exportación')], default='MIN', max_length=3, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(blank=True, help_text='Se autogenera si se deja vacío. Ej: C00001', max_length=20, null=True, unique=True, verbose_name='Código de Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_email',
            field=models.EmailField(blank=True, help_text='Email para envíos de presupuestos, remitos. Puede diferir del fiscal.', max_length=254, null=True, verbose_name='Email Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descuento_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento adicional que aplica siempre sobre el precio de lista.', max_digits=5, verbose_name='Descuento Base (%)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_vencimiento',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 30 = la factura vence a 30 días de emitida.', verbose_name='Días para Vencimiento de Factura'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Fantasía / Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Internas'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Asignado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.CharField(blank=True, help_text='Ej: Zona Norte, Litoral, Gran Buenos Aires', max_length=100, null=True, verbose_name='Zona / Región'),
        ),
    ]
