# Generated by Django 5.2.7 on 2025-12-09 23:26

import django.db.models.deletion
import django.utils.timezone
import parametros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entidades', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImpositiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría Impositiva de Artículo',
                'verbose_name_plural': 'Categorías Impositivas de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre clave del contador, ej: 'codigo_articulo'", max_length=100, unique=True)),
                ('prefijo', models.CharField(default='P', help_text="Prefijo para el código, ej: 'P'", max_length=5)),
                ('ultimo_valor', models.PositiveIntegerField(default=0, verbose_name='Último Valor Utilizado')),
            ],
            options={
                'verbose_name': 'Contador del Sistema',
                'verbose_name_plural': 'Contadores del Sistema',
            },
        ),
        migrations.CreateModel(
            name='GrupoUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Peso, Volumen, Unidades Discretas', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo de Unidad de Medida',
                'verbose_name_plural': 'Grupos de Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: IVA 21%, Impuestos Internos Tabaco', max_length=100, unique=True)),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa/Alícuota (%)')),
                ('es_porcentaje', models.BooleanField(default=True, help_text='Marcar si la tasa es un porcentaje. Desmarcar si es un monto fijo.')),
                ('aplica_a', models.CharField(choices=[('venta', 'Ventas'), ('compra', 'Compras'), ('ambos', 'Ambos')], default='ambos', max_length=10)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.now)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('cotizacion', models.DecimalField(decimal_places=2, help_text='Cotización respecto a la moneda base.', max_digits=10, verbose_name='Cotización')),
                ('es_base', models.BooleanField(default=False, help_text='Marcar si esta es la moneda base del sistema.', verbose_name='¿Es Moneda Base?')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('por_defecto', models.BooleanField(default=False, verbose_name='¿Es el país por defecto?')),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Comprobante')),
                ('codigo_afip', models.CharField(blank=True, help_text='Código de AFIP si corresponde', max_length=3, null=True)),
                ('letra', models.CharField(max_length=1)),
                ('afecta_stock', models.BooleanField(default=False, help_text='Marcar si este comprobante modifica el stock.')),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobante',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresa/')),
                ('nombre_fantasia', models.CharField(help_text='Nombre comercial para el ticket', max_length=200)),
                ('inicio_actividades', models.DateField(verbose_name='Inicio de Actividades')),
                ('ingresos_brutos', models.CharField(max_length=50, verbose_name='N° Ingresos Brutos')),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='entidades.entidad', verbose_name='Entidad Fiscal')),
                ('moneda_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion_principal', to='parametros.moneda')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(default=parametros.models.get_default_pais, on_delete=django.db.models.deletion.PROTECT, to='parametros.pais')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'unique_together': {('nombre', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del rol, ej: Vendedor', max_length=100, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permisos generales asignados.', to='auth.permission')),
                ('users', models.ManyToManyField(blank=True, help_text='Usuarios con este rol.', related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.grupounidadmedida')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('codigo_area_telefonico', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Área')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.provincia')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'unique_together': {('nombre', 'provincia')},
            },
        ),
        migrations.CreateModel(
            name='SerieDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Facturación Electrónica Sucursal Centro', max_length=100, verbose_name='Nombre de la Serie')),
                ('punto_venta', models.PositiveIntegerField(default=1, verbose_name='Punto de Venta (AFIP)')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='Último Número Usado')),
                ('es_manual', models.BooleanField(default=False, help_text='Si se marca, el usuario debe escribir el número (ej: facturas viejas). Si no, es automático.', verbose_name='¿Es numeración manual?')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('deposito_defecto', models.ForeignKey(blank=True, help_text='Si se define, los movimientos de stock afectarán a este depósito automáticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.deposito', verbose_name='Depósito por Defecto')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante Legal')),
            ],
            options={
                'verbose_name': 'Serie de Documento (Talonario)',
                'verbose_name_plural': 'Series de Documentos (Talonarios)',
                'unique_together': {('tipo_comprobante', 'punto_venta')},
            },
        ),
    ]
