# Generated by Django 5.2.7 on 2025-10-07 19:47

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre clave del contador, ej: 'codigo_articulo'", max_length=100, unique=True)),
                ('prefijo', models.CharField(default='P', help_text="Prefijo para el código, ej: 'P'", max_length=5)),
                ('ultimo_valor', models.PositiveIntegerField(default=0, verbose_name='Último Valor Utilizado')),
            ],
            options={
                'verbose_name': 'Contador del Sistema',
                'verbose_name_plural': 'Contadores del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Porcentaje. Ej: 21.00 para 21%', max_digits=5, verbose_name='Tasa')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Símbolo')),
                ('cotizacion', models.DecimalField(decimal_places=2, help_text='Cotización respecto a la moneda base', max_digits=10, verbose_name='Cotización')),
                ('es_base', models.BooleanField(default=False, help_text='Marcar si esta es la moneda base del sistema', verbose_name='¿Es Moneda Base?')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('por_defecto', models.BooleanField(default=False, verbose_name='¿Es el país por defecto?')),
            ],
            options={
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Comprobante')),
                ('codigo_afip', models.CharField(blank=True, help_text='Código de AFIP si corresponde', max_length=3, null=True)),
                ('letra', models.CharField(max_length=1)),
                ('afecta_stock', models.BooleanField(default=False, help_text='Marcar si este comprobante modifica el stock de los artículos.')),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobante',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(default=parametros.models.get_default_pais, on_delete=django.db.models.deletion.PROTECT, to='parametros.pais')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'unique_together': {('nombre', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('codigo_area_telefonico', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Área')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.provincia')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'unique_together': {('nombre', 'provincia')},
            },
        ),
    ]
