# Generated by Django 5.2.7 on 2025-10-23 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Peso, Volumen, Unidades Discretas', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Grupo de Unidad de Medida',
                'verbose_name_plural': 'Grupos de Unidades de Medida',
            },
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.grupounidadmedida'),
        ),
    ]
