# Generated by Django 5.2.7 on 2025-10-25 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_articulo_impuesto'),
        ('parametros', '0002_grupounidadmedida_unidadmedida_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImpositiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría Impositiva de Artículo',
                'verbose_name_plural': 'Categorías Impositivas de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: IVA 21%, Impuestos Internos Tabaco', max_length=100, unique=True)),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa/Alícuota (%)')),
                ('es_porcentaje', models.BooleanField(default=True, help_text='Marcar si la tasa es un porcentaje. Desmarcar si es un monto fijo.')),
                ('aplica_a', models.CharField(choices=[('venta', 'Ventas'), ('compra', 'Compras'), ('ambos', 'Ambos')], default='ambos', max_length=10)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.now)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.DeleteModel(
            name='ReglaImpuesto',
        ),
    ]
