# Generated by Django 5.2.7 on 2025-12-12 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_afipcertificado_afiptoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afipcertificado',
            options={'verbose_name': 'Certificado Digital AFIP', 'verbose_name_plural': 'Certificados Digitales AFIP'},
        ),
        migrations.AddField(
            model_name='afipcertificado',
            name='subido_el',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 12, 2, 31, 4, 445930, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afipcertificado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desactivar certificados vencidos.'),
        ),
        migrations.AlterField(
            model_name='afiptoken',
            name='expira',
            field=models.DateTimeField(),
        ),
    ]
