# Generated by Django 5.2.7 on 2025-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_afipcertificado_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='modo_facturacion',
            field=models.CharField(choices=[('AUTO', 'Automático (Al confirmar venta)'), ('MANUAL', 'Manual (A pedido del usuario)')], default='MANUAL', help_text='Automático: Intenta obtener CAE al guardar. Manual: Requiere acción del usuario.', max_length=10, verbose_name='Modo de Autorización (CAE)'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='usar_factura_electronica',
            field=models.BooleanField(default=True, help_text='Si está activo, el sistema intentará conectar con AFIP.', verbose_name='Habilitar Factura Electrónica'),
        ),
        migrations.AlterField(
            model_name='afipcertificado',
            name='es_produccion',
            field=models.BooleanField(default=False, help_text='Si está marcado, emitirá facturas REALES. Si no, usa servidores de prueba.', verbose_name='¿Es Producción?'),
        ),
        migrations.AlterField(
            model_name='afipcertificado',
            name='nombre',
            field=models.CharField(help_text='Ej: Certificado 2024-2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='afipcertificado',
            name='vencimiento',
            field=models.DateField(blank=True, help_text='Detectado automáticamente desde el archivo .crt', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
