# Generated by Django 5.2.7 on 2025-12-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_configuracionempresa_modo_facturacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaimpositiva',
            name='codigo_afip',
            field=models.IntegerField(default=5, help_text='1=IVA Resp. Inscripto, 5=Consumidor Final, 6=Monotributo, etc. (Ver Tabla AFIP)', verbose_name='Código AFIP (Receptor)'),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='es_fiscal',
            field=models.BooleanField(default=True, help_text='Si está activo, este comprobante pedirá CAE (Esquema Electrónico).', verbose_name='Es Fiscal / Electrónico'),
        ),
    ]
