# Generated by Django 5.2.7 on 2025-12-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_categoriaimpositiva_codigo_afip_and_more'),
        ('ventas', '0007_disenoimpresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriedocumento',
            name='diseno_impresion',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, usa el diseño estándar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.disenoimpresion', verbose_name='Diseño de Impresión (Template)'),
        ),
    ]
