# Generated by Django 5.2.7 on 2025-12-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_seriedocumento_diseno_impresion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Principal', help_text='Ej: Envío Facturas', max_length=50)),
                ('host', models.CharField(choices=[('smtp.gmail.com', 'Gmail'), ('smtp.office365.com', 'Outlook/Office365'), ('smtp.mail.yahoo.com', 'Yahoo'), ('custom', 'Otro / Personalizado')], default='smtp.gmail.com', max_length=100)),
                ('host_custom', models.CharField(blank=True, help_text="Llenar solo si eligió 'Otro'", max_length=100, null=True, verbose_name='Host Personalizado')),
                ('puerto', models.IntegerField(default=587, help_text='587 para TLS, 465 para SSL')),
                ('usuario', models.CharField(help_text='Tu correo electrónico', max_length=100)),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña / App Password')),
                ('usar_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('usar_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('email_from', models.EmailField(help_text='Generalmente igual al usuario', max_length=254, verbose_name="Dirección 'Desde'")),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correo',
            },
        ),
    ]
