# Generated by Django 5.2.7 on 2026-01-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0010_seriedocumento_solicitar_cae_automaticamente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocomprobante',
            name='tipo_stock_afectado',
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='afecta_stock_comprometido',
            field=models.BooleanField(default=False, help_text="Si se marca, aumentará o disminuirá la columna de 'Reservas/Compromisos'.", verbose_name='¿Mueve Stock Comprometido (Reservas)?'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='afecta_stock_fisico',
            field=models.BooleanField(default=True, help_text='Si se marca, aumentará o disminuirá la cantidad real en estantería.', verbose_name='¿Mueve Stock Físico (Real)?'),
        ),
        migrations.AlterField(
            model_name='tipocomprobante',
            name='mueve_stock',
            field=models.BooleanField(default=False, help_text='Interruptor general. Si está apagado, ignora las opciones de abajo.', verbose_name='¿Es Movimiento de Stock?'),
        ),
    ]
