# Generated by Django 5.2.7 on 2026-02-21 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0011_remove_tipocomprobante_tipo_stock_afectado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas_masivas/%Y/%m/', verbose_name='Archivo CSV/Excel')),
                ('entidad', models.CharField(choices=[('ARTICULOS', 'Artículos'), ('PROVEEDORES', 'Proveedores'), ('CLIENTES', 'Clientes')], max_length=50, verbose_name='Entidad a Importar')),
                ('estado', models.CharField(choices=[('PD', 'Pendiente'), ('PR', 'Procesando'), ('OK', 'Completado'), ('ER', 'Error General')], default='PD', max_length=2)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_procesadas', models.IntegerField(default=0)),
                ('filas_exitosas', models.IntegerField(default=0)),
                ('filas_error', models.IntegerField(default=0)),
                ('detalle_errores', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carga Masiva',
                'verbose_name_plural': 'Cargas Masivas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
