# Generated by Django 5.2.7 on 2026-02-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0012_cargamasiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasiva',
            name='modo',
            field=models.CharField(choices=[('CREAR', 'Solo Crear Nuevos (Falla si existe)'), ('ACTUALIZAR', 'Solo Actualizar (Falla si no existe)'), ('AMBOS', 'Crear y Actualizar (Upsert)')], default='AMBOS', max_length=20, verbose_name='Modo de Importación'),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='entidad',
            field=models.CharField(choices=[('ARTICULOS', 'Artículos / Inventario'), ('PRECIOS_VENTA', 'Listas de Precios (Venta)'), ('PRECIOS_COMPRA', 'Listas de Precios (Compra)'), ('CLIENTES', 'Clientes'), ('PROVEEDORES', 'Proveedores')], max_length=50, verbose_name='Entidad a Importar'),
        ),
    ]
