# Generated by Django 5.2.7 on 2025-12-09 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_articulo', models.CharField(help_text='Dejar en blanco para generar código automático.', max_length=20, unique=True, verbose_name='Código Artículo')),
                ('ean', models.CharField(blank=True, db_index=True, help_text='Código de barras EAN-13.', max_length=13, null=True, verbose_name='Código de Barras EAN')),
                ('qr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código QR')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('perfil', models.CharField(choices=[('CV', 'Compra/Venta'), ('CO', 'Compra'), ('VE', 'Venta')], default='CV', max_length=2, verbose_name='Perfil del Artículo')),
                ('precio_costo_monto', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Monto de Costo')),
                ('precio_venta_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto de Venta')),
                ('utilidad', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de ganancia sobre el costo.', max_digits=10, verbose_name='Utilidad (%)')),
                ('administra_stock', models.BooleanField(default=True, verbose_name='¿Administra Stock?')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Pasillo 4, Estantería B', max_length=100, null=True, verbose_name='Ubicación Física')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota Interna')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='ConversionUnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_conversion', models.DecimalField(decimal_places=6, help_text='¿Cuántas unidades de stock (la más pequeña) caben en la unidad externa? Ej: 1 Caja = 150 Unidades.', max_digits=14)),
            ],
            options={
                'verbose_name': 'Factor de Conversión de U.M.',
                'verbose_name_plural': 'Factores de Conversión de U.M.',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si este es el depósito principal.')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='ItemMovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('tipo_movimiento', models.CharField(choices=[('ENT', 'Entrada / Ajuste Positivo'), ('SAL', 'Salida / Ajuste Negativo'), ('TRF', 'Transferencia entre Depósitos')], default='SAL', max_length=3, verbose_name='Tipo de Operación')),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('stock_aplicado', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock Interno',
                'verbose_name_plural': 'Movimientos de Stock Internos',
            },
        ),
        migrations.CreateModel(
            name='ProveedorArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_fuente_de_verdad', models.BooleanField(default=False, help_text='Marcar si este proveedor tiene autoridad para actualizar el precio_costo del artículo.', verbose_name='Fuente de Costo Base')),
                ('fecha_relacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor de Artículo',
                'verbose_name_plural': 'Proveedores de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='StockArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Stock por Depósito',
                'verbose_name_plural': 'Stocks por Depósito',
            },
        ),
    ]
