# Generated by Django 5.2.7 on 2025-10-19 12:26

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='precio_costo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_costo_currency',
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_costo_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda', verbose_name='Moneda de Costo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_costo_monto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Monto de Costo'),
        ),
    ]
