# Generated by Django 5.2.7 on 2025-12-29 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockarticulo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='cantidad_comprometida',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Stock vendido/presupuestado pero aún no entregado.', max_digits=12, verbose_name='Stock Comprometido (Reservado)'),
        ),
        migrations.AddField(
            model_name='stockarticulo',
            name='cantidad_real',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Lo que realmente hay en la estantería.', max_digits=12, verbose_name='Stock Físico Real'),
        ),
        migrations.CreateModel(
            name='HistoricoMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad Ajustada')),
                ('tipo_stock', models.CharField(choices=[('REAL', 'Físico/Real'), ('COMPROMETIDO', 'Comprometido/Reserva')], max_length=15)),
                ('operacion', models.CharField(choices=[('SUMAR', 'Suma (+)'), ('RESTAR', 'Resta (-)')], max_length=10)),
                ('saldo_post_movimiento', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo Resultante')),
                ('referencia', models.CharField(blank=True, help_text="Ej: 'Venta 0001-00000055' o 'Ajuste Manual'", max_length=150, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
