# Generated by Django 5.2.7 on 2025-10-23 03:14

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_articulo_precio_costo_and_more'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida_venta',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, help_text='La unidad en la que se vende el artículo por defecto (ej: Caja).', on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta', to='parametros.unidadmedida', verbose_name='Unidad de Medida de Venta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida_stock',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, help_text='La unidad en la que se controla el inventario (la más pequeña).', on_delete=django.db.models.deletion.PROTECT, related_name='articulos_stock', to='parametros.unidadmedida', verbose_name='Unidad de Medida de Stock'),
        ),
    ]
