# Generated by Django 5.2.7 on 2025-11-25 02:44

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_articulo_impuesto_and_more'),
        ('parametros', '0002_categoriaimpositiva_grupounidadmedida_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria_impositiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.categoriaimpositiva', verbose_name='Categoría Impositiva'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras EAN-13.', max_length=13, null=True, verbose_name='Código de Barras EAN'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo_unidades',
            field=models.ForeignKey(blank=True, help_text='Define la categoría de unidades del artículo (Peso, Volumen, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.grupounidadmedida', verbose_name='Grupo de Unidades'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='impuestos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione todos los impuestos que aplican a este artículo (IVA, Internos, etc.)', to='parametros.impuesto', verbose_name='Impuestos Aplicables'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_costo_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_costo', to='parametros.moneda', verbose_name='Moneda de Costo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_costo_monto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Monto de Costo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta_moneda', to='parametros.moneda', verbose_name='Moneda de Venta'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto de Venta'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='qr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código QR'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida_venta',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta', to='parametros.unidadmedida', verbose_name='U.M. de Venta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida_stock',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_stock', to='parametros.unidadmedida', verbose_name='U.M. de Stock'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de ganancia sobre el costo.', max_digits=10, verbose_name='Utilidad (%)'),
        ),
    ]
