# Generated by Django 5.2.7 on 2026-01-13 13:57

import django.db.models.deletion
import django.utils.timezone
import parametros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_stockarticulo_cantidad_and_more'),
        ('parametros', '0011_remove_tipocomprobante_tipo_stock_afectado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Clave única (ej: REAL, RSRV)', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('es_fisico', models.BooleanField(default=False, help_text='¿La mercadería está físicamente en el depósito?')),
                ('es_vendible', models.BooleanField(default=False, help_text='¿Suma al stock disponible para venta?')),
                ('es_reservado', models.BooleanField(default=False, help_text='¿Resta del stock disponible?')),
            ],
            options={
                'verbose_name': 'Configuración de Tipo de Stock',
                'verbose_name_plural': 'Tipos de Stock (Config)',
            },
        ),
        migrations.AlterModelOptions(
            name='historicomovimientos',
            options={'verbose_name': 'Histórico Legacy (Deprecado)', 'verbose_name_plural': 'Historial Legacy'},
        ),
        migrations.AlterModelOptions(
            name='stockarticulo',
            options={'verbose_name': 'Stock por Depósito (Legacy)', 'verbose_name_plural': 'Stocks por Depósito (Legacy)'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cod_articulo',
            field=models.CharField(help_text='Dejar en blanco para autogenerar.', max_length=20, unique=True, verbose_name='Código Artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='perfil',
            field=models.CharField(choices=[('CV', 'Compra/Venta'), ('CO', 'Compra'), ('VE', 'Venta')], default='CV', max_length=2, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_costo_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_costo', to='parametros.moneda', verbose_name='Moneda Costo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_costo_monto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_venta_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta_moneda', to='parametros.moneda', verbose_name='Moneda Venta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_venta_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='historicomovimientos',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='historicomovimientos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicomovimientos',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicomovimientos',
            name='saldo_post_movimiento',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockarticulo',
            name='cantidad_comprometida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Comprometido'),
        ),
        migrations.AlterField(
            model_name='stockarticulo',
            name='cantidad_real',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Físico Real'),
        ),
        migrations.CreateModel(
            name='MovimientoStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Efectiva')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Positivo=Entra, Negativo=Sale', max_digits=15)),
                ('origen_sistema', models.CharField(help_text="Ej: 'VENTAS', 'COMPRAS', 'AJUSTE', 'MIGRACION'", max_length=50)),
                ('origen_referencia', models.CharField(help_text="Ej: 'FC-A 0001-00001234' o ID interno", max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipostock')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock (Ledger)',
                'verbose_name_plural': 'Ledger de Stock',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['articulo', 'deposito', 'fecha_movimiento'], name='inventario__articul_8c04f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BalanceStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances_stock', to='inventario.articulo')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances_stock', to='inventario.deposito')),
                ('tipo_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipostock')),
            ],
            options={
                'verbose_name': 'Balance de Stock',
                'verbose_name_plural': 'Balances de Stock',
                'indexes': [models.Index(fields=['articulo', 'deposito'], name='inventario__articul_57e551_idx')],
                'unique_together': {('articulo', 'deposito', 'tipo_stock')},
            },
        ),
    ]
