# Generated by Django 5.2.7 on 2025-11-27 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_articulo_categoria_impositiva_articulo_ean_and_more'),
        ('parametros', '0003_seriedocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('tipo_movimiento', models.CharField(choices=[('ENT', 'Entrada / Ajuste Positivo'), ('SAL', 'Salida / Ajuste Negativo'), ('TRF', 'Transferencia entre Depósitos')], default='SAL', max_length=3, verbose_name='Tipo de Operación')),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado (Afecta Stock)'), ('CA', 'Cancelado')], default='BR', max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deposito_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.deposito', verbose_name='Depósito Destino (Entra aquí)')),
                ('deposito_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.deposito', verbose_name='Depósito Origen (Sale de aquí)')),
                ('serie', models.ForeignKey(help_text="Ej: 'Ajuste Inventario', 'Transferencia Sucursal 1'", on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Concepto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock Interno',
                'verbose_name_plural': 'Movimientos de Stock Internos',
            },
        ),
        migrations.CreateModel(
            name='ItemMovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.movimientostock')),
            ],
        ),
    ]
