# Generated by Django 5.2.7 on 2025-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientostock_itemmovimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='stock_aplicado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='estado',
            field=models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2),
        ),
    ]
