# Generated by Django 5.2.7 on 2025-10-23 12:57

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_articulo_grupo_unidades_and_more'),
        ('parametros', '0002_grupounidadmedida_unidadmedida_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='precio_venta_currency',
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_venta_moneda', to='parametros.moneda', verbose_name='Moneda de Venta'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio_venta_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto de Venta'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio_costo_moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, related_name='articulos_costo', to='parametros.moneda', verbose_name='Moneda de Costo'),
        ),
    ]
