# Generated by Django 5.2.7 on 2025-10-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_articulo_precio_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='impuesto',
        ),
    ]
