# Generated by Django 5.2.7 on 2025-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_articulo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Pasillo 4, Estantería B', max_length=100, null=True, verbose_name='Ubicación Física'),
        ),
    ]
