# Generated by Django 5.2.7 on 2025-10-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_articulo_impuesto'),
        ('parametros', '0003_categoriaimpositiva_impuesto_delete_reglaimpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria_impositiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.categoriaimpositiva', verbose_name='Categoría Impositiva'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='impuestos',
            field=models.ManyToManyField(blank=True, help_text='Seleccione todos los impuestos que aplican a este artículo (IVA, Internos, etc.)', to='parametros.impuesto', verbose_name='Impuestos Aplicables'),
        ),
    ]
