# Generated by Django 5.2.7 on 2026-01-17 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_seed_tipos_stock_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('TR', 'En Tránsito (Enviado)'), ('CP', 'Completada (Recibida)'), ('AN', 'Anulada')], default='BR', max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('movimiento_salida_aplicado', models.BooleanField(default=False, editable=False)),
                ('movimiento_entrada_aplicado', models.BooleanField(default=False, editable=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_inventario', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='inventario.deposito', verbose_name='Depósito Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='inventario.deposito', verbose_name='Depósito Origen')),
            ],
            options={
                'verbose_name': 'Transferencia entre Depósitos',
                'verbose_name_plural': 'Transferencias entre Depósitos',
                'permissions': [('enviar_transferencia', 'Puede enviar mercadería (Salida)'), ('recibir_transferencia', 'Puede recibir mercadería (Entrada)')],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.transferenciainterna')),
            ],
        ),
    ]
