# Generated by Django 5.2.7 on 2025-10-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_articulo_categoria_impositiva_articulo_impuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='ean',
            field=models.CharField(blank=True, db_index=True, help_text='Código de barras EAN-13.', max_length=13, null=True, verbose_name='Código de Barras EAN'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='qr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código QR'),
        ),
    ]
