# Generated by Django 5.2.7 on 2026-03-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_ajustestock_fecha_alter_movimientostock_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto (cm)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho (cm)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='cod_fabricante',
            field=models.CharField(blank=True, db_index=True, help_text='Código original del fabricante. Útil para búsqueda y compatibilidad.', max_length=50, null=True, verbose_name='Código del Fabricante / OEM'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Para catálogos, e-commerce, fichas PDF.', null=True, verbose_name='Descripción Larga / Ficha Técnica'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='es_bien_de_uso',
            field=models.BooleanField(default=False, help_text='Activos que se amortizan. No se venden habitualmente.', verbose_name='¿Es Bien de Uso / Activo Fijo?'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Los servicios no administran stock. Ej: Mano de obra, Flete.', verbose_name='¿Es un Servicio?'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='garantia_meses',
            field=models.PositiveIntegerField(default=0, verbose_name='Garantía (meses)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='lead_time_dias',
            field=models.PositiveIntegerField(default=0, help_text='Días de demora desde que se ordena hasta que llega.', verbose_name='Lead Time (días)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='profundidad_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profundidad (cm)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Para control de sobrestock. 0 = sin límite.', max_digits=10, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Cuando el stock baje de este valor, se genera alerta.', max_digits=10, verbose_name='Stock Mínimo (Punto de Reposición)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock_seguridad',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Colchón de emergencia, no se toca salvo urgencia.', max_digits=10, verbose_name='Stock de Seguridad'),
        ),
        migrations.AddField(
            model_name='proveedorarticulo',
            name='cod_articulo_proveedor',
            field=models.CharField(blank=True, help_text='El código con el que este proveedor identifica al artículo en sus facturas/remitos.', max_length=50, null=True, verbose_name='Código en el Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedorarticulo',
            name='descripcion_proveedor',
            field=models.CharField(blank=True, help_text='Cómo lo llama el proveedor en sus documentos. Facilita el reconocimiento automático en compras.', max_length=255, null=True, verbose_name='Descripción en el Proveedor'),
        ),
    ]
