# Generated by Django 5.2.7 on 2025-10-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, unique=True, verbose_name='Razón Social / Nombre y Apellido')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('J', 'Persona Jurídica')], max_length=1, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI')),
                ('cuit', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CUIT/CUIL')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='EntidadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email',
            },
        ),
        migrations.CreateModel(
            name='EntidadTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('FIJO', 'Fijo'), ('CEL', 'Celular'), ('FAX', 'Fax'), ('COM', 'Comercial')], default='CEL', max_length=4)),
            ],
            options={
                'verbose_name': 'Teléfono',
            },
        ),
        migrations.CreateModel(
            name='SituacionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Situación frente al IVA',
                'verbose_name_plural': 'Situaciones frente al IVA',
            },
        ),
        migrations.CreateModel(
            name='EntidadDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Domicilio',
            },
        ),
    ]
