# Generated by Django 5.2.7 on 2025-10-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidaddomicilio',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.localidad'),
        ),
        migrations.AddField(
            model_name='entidademail',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='entidades.entidad'),
        ),
        migrations.AddField(
            model_name='entidadtelefono',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='entidades.entidad'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='situacion_iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entidades.situacioniva', verbose_name='Situación IVA'),
        ),
    ]
