# Generated by Django 5.2.7 on 2025-12-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacioniva',
            name='codigo_afip',
            field=models.IntegerField(default=5, help_text='1=IVA Resp. Inscripto, 5=Consumidor Final, 6=Monotributo (Ver Tabla AFIP)', verbose_name='Código AFIP (Receptor)'),
        ),
    ]
