# Generated by Django 5.2.7 on 2026-03-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0005_cliente_enterprise_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entidaddomicilio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entidademail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entidadtelefono',
            options={},
        ),
        migrations.AlterModelOptions(
            name='situacioniva',
            options={'ordering': ['codigo', 'nombre'], 'verbose_name': 'Situación IVA', 'verbose_name_plural': 'Situaciones IVA'},
        ),
        migrations.RemoveField(
            model_name='entidaddomicilio',
            name='es_entrega',
        ),
        migrations.RemoveField(
            model_name='entidaddomicilio',
            name='es_fiscal',
        ),
        migrations.RemoveField(
            model_name='entidademail',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='entidadtelefono',
            name='tipo',
        ),
        migrations.AddField(
            model_name='entidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='numero_iibb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='razon_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='situacion_iibb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='situacion_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entidades.situacioniva'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT'), ('CUIL', 'CUIL'), ('PAS', 'Pasaporte'), ('OTR', 'Otro')], default='CUIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_persona',
            field=models.CharField(choices=[('F', 'Persona Física'), ('J', 'Persona Jurídica')], default='J', max_length=1),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='calle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='dpto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='localidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entidademail',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='entidades.entidad'),
        ),
        migrations.AlterField(
            model_name='entidadtelefono',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='situacioniva',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='situacioniva',
            name='codigo_afip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='situacioniva',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
