# Generated by Django 5.2.7 on 2026-06-12 04:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0007_situacioniva_mostrar_precio_con_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='entidaddomicilio',
            options={'verbose_name': 'Domicilio', 'verbose_name_plural': 'Domicilios'},
        ),
        migrations.AlterModelOptions(
            name='entidademail',
            options={'verbose_name': 'Email Adicional', 'verbose_name_plural': 'Emails Adicionales'},
        ),
        migrations.AlterModelOptions(
            name='entidadtelefono',
            options={'verbose_name': 'Teléfono', 'verbose_name_plural': 'Teléfonos'},
        ),
        migrations.AlterModelOptions(
            name='situacioniva',
            options={'verbose_name': 'Situación frente al IVA', 'verbose_name_plural': 'Situaciones frente al IVA'},
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='nombre_fantasia',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='numero_documento',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='numero_iibb',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='situacion_iibb',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='web',
        ),
        migrations.AddField(
            model_name='entidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='entidademail',
            name='tipo',
            field=models.CharField(default='Secundario', help_text='Ej: Administración, Compras', max_length=50),
        ),
        migrations.AddField(
            model_name='entidadtelefono',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('CEL', 'Celular'), ('FAX', 'Fax'), ('COM', 'Comercial')], default='CEL', max_length=4),
        ),
        migrations.AddField(
            model_name='situacioniva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacioniva',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='situacioniva',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='situacioniva',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='situacioniva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AddField(
            model_name='situacioniva',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='CUIT/CUIL'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Facturación'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='razon_social',
            field=models.CharField(max_length=255, unique=True, verbose_name='Razón Social / Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('J', 'Persona Jurídica')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='situacion_iva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='entidades.situacioniva', verbose_name='Situación IVA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT/CUIL'), ('OTRO', 'Otro')], default='CUIT', max_length=10, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='tipo_persona',
            field=models.CharField(choices=[('F', 'Persona Física'), ('J', 'Persona Jurídica')], default='J', max_length=1, verbose_name='Tipo de Persona'),
        ),
        migrations.AlterField(
            model_name='entidaddomicilio',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entidademail',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_secundarios', to='entidades.entidad'),
        ),
        migrations.AlterField(
            model_name='entidadtelefono',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='situacioniva',
            name='codigo',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='situacioniva',
            name='codigo_afip',
            field=models.IntegerField(default=5, help_text='1=IVA Resp. Inscripto, 5=Consumidor Final, 6=Monotributo', verbose_name='Código AFIP (Receptor)'),
        ),
        migrations.AlterField(
            model_name='situacioniva',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
