# Generated by Django 5.2.7 on 2025-10-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(editable=False, max_length=1)),
                ('punto_venta', models.PositiveIntegerField(default=1, verbose_name='Punto de Venta')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha del Comprobante')),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('FN', 'Finalizado'), ('AN', 'Anulado')], default='BR', max_length=2, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('impuestos', models.JSONField(default=dict, editable=False, help_text='Desglose de impuestos calculados')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente', verbose_name='Cliente')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante')),
            ],
            options={
                'verbose_name': 'Comprobante de Venta',
                'verbose_name_plural': 'Comprobantes de Venta',
                'unique_together': {('tipo_comprobante', 'punto_venta', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo', verbose_name='Artículo')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.comprobanteventa')),
            ],
        ),
    ]
