# Generated by Django 5.2.7 on 2025-12-09 23:26

import django.db.models.deletion
import django.utils.timezone
import ventas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='entidades.entidad')),
                ('permite_cta_cte', models.BooleanField(default=False, help_text='Si está desactivado, este cliente solo puede operar de CONTADO.', verbose_name='Habilitar Cuenta Corriente')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Es la lista por defecto?')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento general (%)')),
                ('formula', models.CharField(blank=True, help_text="Ej: 'costo * 1.5 + 50'. Usa 'costo' como variable. Se aplica si no hay precio específico.", max_length=255, verbose_name='Fórmula de Precio Personalizada')),
            ],
            options={
                'verbose_name': 'Lista de Precios de Venta',
                'verbose_name_plural': 'Listas de Precios de Venta',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('letra', models.CharField(editable=False, max_length=1)),
                ('punto_venta', models.PositiveIntegerField(default=1, verbose_name='Punto de Venta')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Comprobante')),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('condicion_venta', models.CharField(choices=[('CO', 'Contado'), ('CC', 'Cuenta Corriente')], default='CO', max_length=2)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('impuestos', models.JSONField(default=dict, editable=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('stock_aplicado', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente', verbose_name='Cliente')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Talonario')),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante')),
            ],
            options={
                'verbose_name': 'Comprobante de Venta',
                'verbose_name_plural': 'Comprobantes de Venta',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo', verbose_name='Artículo')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.comprobanteventa')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pricelist', verbose_name='Lista de Precios Asignada'),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('finanzas_aplicadas', models.BooleanField(default=False, editable=False)),
                ('origen', models.CharField(choices=[('CTA', 'Cobranza Cuenta Corriente'), ('CON', 'Venta Contado')], default='CTA', max_length=3, verbose_name='Origen de Fondos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento')),
            ],
            options={
                'verbose_name': 'Recibo de Cobro',
                'verbose_name_plural': 'Recibos de Cobro',
            },
        ),
        migrations.CreateModel(
            name='ReciboImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_imputado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.comprobanteventa')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='ventas.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('cuit_librador', models.CharField(blank=True, max_length=11)),
                ('banco_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.banco')),
                ('cheque_tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cheque')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentafondo', verbose_name='Caja/Cuenta Destino')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='ventas.recibo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto del Precio')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Cantidad Mínima')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cantidad Máxima')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='ventas.pricelist')),
                ('price_moneda', models.ForeignKey(default=ventas.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_prices', to='inventario.articulo')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'price_list', 'min_quantity')},
            },
        ),
    ]
