# Generated by Django 5.2.7 on 2025-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones / Notas'),
        ),
    ]
