# Generated by Django 5.2.7 on 2025-10-25 17:56

import django.db.models.deletion
import ventas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('parametros', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válido Desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido Hasta')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Es la lista por defecto?')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento general (%)')),
            ],
            options={
                'verbose_name': 'Lista de Precios de Venta',
                'verbose_name_plural': 'Listas de Precios de Venta',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.pricelist', verbose_name='Lista de Precios Asignada'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto del Precio')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Cantidad Mínima')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Cantidad Máxima')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='ventas.pricelist')),
                ('price_moneda', models.ForeignKey(default=ventas.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_prices', to='inventario.articulo')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'price_list', 'min_quantity')},
            },
        ),
    ]
