# Generated by Django 5.2.7 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_comprobanteventa_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='afip_error',
            field=models.TextField(blank=True, null=True, verbose_name='Error AFIP'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='afip_xml_request',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='afip_xml_response',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='cae',
            field=models.CharField(blank=True, help_text='Código de Autorización Electrónico', max_length=50, null=True, verbose_name='CAE'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='vto_cae',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento CAE'),
        ),
    ]
