# Generated by Django 5.2.7 on 2025-11-26 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_seriedocumento'),
        ('ventas', '0003_pricelist_formula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comprobanteventa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Seleccione la serie para numeración automática', null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Talonario'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
