# Generated by Django 5.2.7 on 2025-12-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_comprobanteventa_afip_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePendienteCAE',
            fields=[
            ],
            options={
                'verbose_name': '⚠️ Bandeja Factura Electrónica',
                'verbose_name_plural': '⚠️ Bandeja Factura Electrónica (Pendientes)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ventas.comprobanteventa',),
        ),
    ]
