# Generated by Django 5.2.7 on 2025-11-27 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_comprobanteventa_tipo_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='stock_aplicado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='estado',
            field=models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Comprobante'),
        ),
    ]
