# Generated by Django 5.2.7 on 2025-11-27 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_centrocosto_alter_movimientofondo_options_and_more'),
        ('parametros', '0003_seriedocumento'),
        ('ventas', '0006_comprobanteventa_stock_aplicado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('finanzas_aplicadas', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Talonario')),
            ],
            options={
                'verbose_name': 'Recibo de Cobro',
                'verbose_name_plural': 'Recibos de Cobro',
            },
        ),
        migrations.CreateModel(
            name='ReciboImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_imputado', models.DecimalField(decimal_places=2, help_text='Cuánto de este recibo va a esta factura', max_digits=14)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.comprobanteventa', verbose_name='Comprobante a Pagar')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='ventas.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='N° Cheque / Lote / Ref')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='Fecha de Cobro (Cheque)')),
                ('cuit_librador', models.CharField(blank=True, max_length=11, verbose_name='CUIT Librador (Cheque)')),
                ('banco_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.banco', verbose_name='Banco (Cheque/Transf)')),
                ('cheque_tercero', models.ForeignKey(blank=True, help_text='Solo si redeposita un cheque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cheque')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentafondo', verbose_name='Caja/Cuenta Destino')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='ventas.recibo')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor')),
            ],
        ),
    ]
