# Generated by Django 5.2.7 on 2025-11-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_seriedocumento'),
        ('ventas', '0008_cliente_limite_credito_cliente_permite_cta_cte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Talonario'),
        ),
    ]
