# Generated by Django 5.2.7 on 2025-12-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_disenoimpresion_contenido_html_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disenoimpresion',
            options={'verbose_name': 'Diseño de Impresión y Email', 'verbose_name_plural': 'Diseños de Impresión y Email'},
        ),
        migrations.AddField(
            model_name='disenoimpresion',
            name='asunto_email',
            field=models.CharField(blank=True, help_text='Ej: Factura {numero} de {empresa}', max_length=200, null=True, verbose_name='Asunto del Email'),
        ),
        migrations.AddField(
            model_name='disenoimpresion',
            name='cuerpo_email',
            field=models.TextField(blank=True, help_text='Variables disponibles: {cliente}, {numero}, {fecha}, {empresa}, {vencimiento}. Salto de línea funciona.', null=True, verbose_name='Cuerpo del Email'),
        ),
        migrations.AlterField(
            model_name='disenoimpresion',
            name='archivo_template',
            field=models.CharField(default='ventas/pdf/factura_premium.html', help_text='Ej: ventas/pdf/factura_premium.html', max_length=100, verbose_name='Ruta del Template PDF'),
        ),
    ]
