# Generated by Django 5.2.7 on 2025-12-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_disenoimpresion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='comprobante_asociado',
            field=models.ForeignKey(blank=True, help_text='Si es una Nota de Crédito/Débito, aquí se vincula la Factura original del sistema.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_asociadas', to='ventas.comprobanteventa', verbose_name='Comprobante de Origen'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='periodo_asociado_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo Asoc. Hasta'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='periodo_asociado_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo Asoc. Desde'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Usar solo si el comprobante de origen no está en este sistema. Formato: 001-00001234', max_length=100, null=True, verbose_name='Ref. Comprobante Externo'),
        ),
    ]
