# Generated by Django 5.2.7 on 2025-12-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_seriedocumento'),
        ('ventas', '0010_alter_productprice_options_recibo_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento'),
        ),
    ]
