# Generated by Django 5.2.7 on 2025-12-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_comprobanteventa_comprobante_asociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='comprobante_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_asociadas', to='ventas.comprobanteventa', verbose_name='Comprobante de Origen'),
        ),
        migrations.AlterField(
            model_name='comprobanteventa',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Formato: PuntoVenta-Numero (Ej: 1-123). Usar solo si no se selecciona un comprobante asociado del sistema.', max_length=100, null=True, verbose_name='Ref. Comprobante Externo'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='origen',
            field=models.CharField(choices=[('CTA', 'Cobranza Cuenta Corriente'), ('CON', 'Venta Contado'), ('DEV', 'Devolución (Salida de Dinero)')], default='CTA', max_length=3, verbose_name='Origen de Fondos'),
        ),
    ]
