# Generated by Django 5.2.7 on 2025-12-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_comprobanteventa_comprobante_asociado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='comprobante_asociado',
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='comprobantes_asociados',
            field=models.ManyToManyField(blank=True, related_name='notas_asociadas', to='ventas.comprobanteventa', verbose_name='Comprobantes de Origen'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='concepto_nota_credito',
            field=models.CharField(blank=True, choices=[('DEV', 'Devolución de Mercadería (Mueve Stock)'), ('FIN', 'Ajuste Financiero / Descuento (No Mueve Stock)'), ('ANU', 'Anulación de Operación (Mueve Stock)')], help_text='Define si se debe reintegrar el stock o solo ajustar saldo.', max_length=3, null=True, verbose_name='Motivo de Nota de Crédito'),
        ),
    ]
