# Generated by Django 5.2.7 on 2026-02-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_remove_plantarjeta_coeficiente_and_more'),
        ('ventas', '0016_alter_comprobantecobroitem_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecobroitem',
            name='tarjeta_plan',
        ),
        migrations.AddField(
            model_name='comprobantecobroitem',
            name='opcion_cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.plancuota', verbose_name='Plan y Cuotas'),
        ),
        migrations.AlterField(
            model_name='comprobantecobroitem',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto a cobrar (El sistema sumará el recargo si corresponde)', max_digits=14),
        ),
    ]
