# Generated by Django 5.2.7 on 2026-02-25 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_remove_comprobantecobroitem_tarjeta_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Comprobante'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
