# Generated by Django 5.2.7 on 2026-03-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_alter_comprobanteventa_fecha_alter_recibo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='letra',
            field=models.CharField(blank=True, default='', editable=False, max_length=1),
        ),
    ]
