# Generated by Django 5.2.7 on 2026-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_cliente_categoria_cliente_codigo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='cliente_cuit_override',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='CUIT / DNI (Override)'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='cliente_email_override',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Override)'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='cliente_nombre_override',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre / Razón Social (Override)'),
        ),
    ]
