# Generated by Django 5.2.7 on 2025-10-08 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.deposito'),
        ),
    ]
