# Generated by Django 5.2.7 on 2025-10-14 01:59

import django.db.models.deletion
import parametros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0003_initial'),
        ('inventario', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.tipocomprobante', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.articulo', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='comprobantecompraitem',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.comprobantecompra'),
        ),
        migrations.AddField(
            model_name='precioproveedorarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_de_proveedores', to='inventario.articulo'),
        ),
        migrations.AddField(
            model_name='precioproveedorarticulo',
            name='unidad_medida_compra',
            field=models.ForeignKey(default=parametros.models.get_default_unidad_medida, on_delete=django.db.models.deletion.PROTECT, to='parametros.unidadmedida', verbose_name='U. de Medida de Compra'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles que pueden gestionar este proveedor.', to='parametros.role'),
        ),
        migrations.AddField(
            model_name='precioproveedorarticulo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='ProveedorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Lista de Precio de Proveedor',
                'verbose_name_plural': 'Listas de Precios de Proveedores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('compras.proveedor',),
        ),
        migrations.AlterUniqueTogether(
            name='precioproveedorarticulo',
            unique_together={('proveedor', 'articulo', 'cantidad_minima', 'unidad_medida_compra')},
        ),
    ]
