# Generated by Django 5.2.7 on 2025-11-27 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Comprobante'),
        ),
        migrations.AlterField(
            model_name='listapreciosproveedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='listapreciosproveedor',
            name='es_principal',
            field=models.BooleanField(default=False, verbose_name='¿Es la Lista Principal?'),
        ),
        migrations.AlterField(
            model_name='listapreciosproveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Lista'),
        ),
        migrations.AlterField(
            model_name='listapreciosproveedor',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Vigente Hasta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Proveedor'),
        ),
    ]
