# Generated by Django 5.2.7 on 2025-10-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='limite_credito_currency',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito'),
        ),
    ]
