# Generated by Django 5.2.7 on 2026-02-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_ordenpagovalor_es_echeq'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nro_iibb',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° IIBB'),
        ),
    ]
