# Generated by Django 5.2.7 on 2026-02-25 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_proveedor_regimen_ganancias_proveedor_regimen_iibb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecompra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Comprobante'),
        ),
        migrations.AlterField(
            model_name='ordenpago',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
