# Generated by Django 5.2.7 on 2025-11-28 03:22

import compras.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_comprobantecompra_stock_aplicado_and_more'),
        ('finanzas', '0002_centrocosto_alter_movimientofondo_options_and_more'),
        ('parametros', '0003_seriedocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecompra',
            name='condicion_compra',
            field=models.CharField(choices=[('CO', 'Contado'), ('CC', 'Cuenta Corriente')], default='CC', max_length=2, verbose_name='Condición'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='impuestos',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='comprobantecompra',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie (Opcional)'),
        ),
        migrations.AlterField(
            model_name='historialprecioproveedor',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='bonificacion_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bonif (%)'),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='codigo_articulo_proveedor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='descuentos_adicionales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='descuentos_financieros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='precio_lista_moneda',
            field=models.ForeignKey(default=compras.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda'),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='precio_lista_monto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='itemlistapreciosproveedor',
            name='unidad_medida_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametros.unidadmedida', verbose_name='Unidad Compra'),
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('finanzas_aplicadas', models.BooleanField(default=False, editable=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametros.seriedocumento', verbose_name='Serie / Talonario')),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Órdenes de Pago',
            },
        ),
        migrations.CreateModel(
            name='OrdenPagoImputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_imputado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.comprobantecompra', verbose_name='Factura a Pagar')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='compras.ordenpago')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPagoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cheque_propio_nro', models.CharField(blank=True, max_length=50, verbose_name='N° Cheque Propio')),
                ('fecha_pago_cheque', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Ref/Transf')),
                ('cheque_tercero', models.ForeignKey(blank=True, help_text='Seleccionar cheque de cartera para endosar', limit_choices_to={'estado': 'CA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cheque')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='compras.ordenpago')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentafondo', verbose_name='Caja/Cuenta Origen')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor')),
            ],
        ),
    ]
