# Generated by Django 5.2.7 on 2026-03-16 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_comprobantecompra_fecha_alter_ordenpago_fecha'),
        ('parametros', '0013_cargamasiva_modo_alter_cargamasiva_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='banco_alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alias CBU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_cbu',
            field=models.CharField(blank=True, max_length=22, null=True, verbose_name='CBU'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_cuenta_nro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Cuenta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_tipo_cuenta',
            field=models.CharField(blank=True, help_text='Ej: Cta Cte, Caja de Ahorros', max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto Comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento habitual que otorga este proveedor.', max_digits=5, verbose_name='Descuento de Compra (%)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='¿Está Activo?'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_alta',
            field=models.DateField(blank=True, help_text='Fecha en que se dio de alta el proveedor.', null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda_compra',
            field=models.ForeignKey(blank=True, help_text='USD para importaciones, ARS para locales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_moneda_compra', to='parametros.moneda', verbose_name='Moneda de Compra Default'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plazo_pago_dias',
            field=models.PositiveIntegerField(default=0, help_text='Ej: 30 = pago a 30 días de la factura.', verbose_name='Plazo de Pago (días)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Proveedor'),
        ),
    ]
