# Generated by Django 5.2.7 on 2026-06-12 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_remove_listapreciosproveedor_es_activa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantecompra',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='comprobantecompra',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='listapreciosproveedor',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='listapreciosproveedor',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='ordenpago',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_por',
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='comprobantecompra',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='listapreciosproveedor',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='listapreciosproveedor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla para eliminar (Soft Delete)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
