# Generated by Django 5.2.7 on 2025-11-27 20:41

import django.db.models.deletion
import django.utils.timezone
import parametros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0003_seriedocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo_bcra', models.CharField(blank=True, max_length=10, verbose_name='Código BCRA')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='TipoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('requiere_banco', models.BooleanField(default=False, help_text='Si es True, pide seleccionar un banco (ej: Transferencia).')),
                ('es_cheque', models.BooleanField(default=False, help_text='Si es True, habilita la gestión de cheques.')),
                ('es_tarjeta', models.BooleanField(default=False, help_text='Si es True, habilita campos de tarjeta (Lote, Cupón).')),
            ],
            options={
                'verbose_name': 'Tipo de Valor',
                'verbose_name_plural': 'Tipos de Valores',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('P', 'Propio (Emitido)'), ('T', 'Tercero (Recibido)')], default='T', max_length=1)),
                ('estado', models.CharField(choices=[('CA', 'En Cartera'), ('DE', 'Depositado'), ('CO', 'Cobrado / Acreditado'), ('EN', 'Entregado a Tercero'), ('RE', 'Rechazado'), ('AN', 'Anulado')], default='CA', max_length=2)),
                ('numero', models.CharField(max_length=50, verbose_name='N° Cheque')),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago / Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuit_librador', models.CharField(blank=True, max_length=11, verbose_name='CUIT Librador')),
                ('nombre_librador', models.CharField(blank=True, max_length=100, verbose_name='Nombre Librador')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.banco', verbose_name='Banco Emisor')),
                ('moneda', models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Caja Principal, Banco Nación CC$', max_length=100)),
                ('tipo', models.CharField(choices=[('EF', 'Caja / Efectivo'), ('BA', 'Cuenta Bancaria'), ('VI', 'Billetera Virtual (MP, etc)')], default='EF', max_length=2)),
                ('saldo_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo Actual')),
                ('cbu', models.CharField(blank=True, max_length=22, verbose_name='CBU / CVU')),
                ('activa', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.banco')),
                ('moneda', models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda')),
            ],
            options={
                'verbose_name': 'Cuenta de Fondos / Caja',
                'verbose_name_plural': 'Cuentas de Fondos / Cajas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_movimiento', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso'), ('TR', 'Transferencia Interna')], max_length=2)),
                ('monto_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('concepto', models.CharField(help_text='Ej: Cobro Factura F-0001, Pago Luz', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cheque')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuentafondo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_valor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor')),
            ],
        ),
    ]
