# Generated by Django 5.2.7 on 2025-12-09 23:26

import django.db.models.deletion
import parametros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda'),
        ),
        migrations.AddField(
            model_name='cuentafondo',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.banco'),
        ),
        migrations.AddField(
            model_name='cuentafondo',
            name='moneda',
            field=models.ForeignKey(default=parametros.models.get_default_moneda_pk, on_delete=django.db.models.deletion.PROTECT, to='parametros.moneda'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.centrocosto', verbose_name='Centro de Costo'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cheque'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuentafondo'),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='tipo_valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tipovalor'),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='finanzas.cuentafondo', verbose_name='Cuenta Destino'),
        ),
        migrations.AddField(
            model_name='transferenciainterna',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='finanzas.cuentafondo', verbose_name='Cuenta Origen'),
        ),
    ]
