# Generated by Django 5.2.7 on 2025-12-06 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_centrocosto_alter_movimientofondo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(blank=True, default='Transferencia interna de fondos', max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='N° de Transacción Bancaria o Lote', max_length=100)),
                ('estado', models.CharField(choices=[('BR', 'Borrador'), ('CN', 'Confirmado'), ('AN', 'Anulado')], default='BR', max_length=2)),
                ('finanzas_aplicadas', models.BooleanField(default=False, editable=False)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='finanzas.cuentafondo', verbose_name='Cuenta Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='finanzas.cuentafondo', verbose_name='Cuenta Origen')),
            ],
            options={
                'verbose_name': 'Transferencia Interna / Depósito',
                'verbose_name_plural': 'Transferencias Internas / Depósitos',
            },
        ),
    ]
