# Generated by Django 5.2.7 on 2026-02-17 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_regimenretencion_certificadoretencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuponTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, help_text='N° de Lote de la terminal POS', max_length=20)),
                ('cupon', models.CharField(max_length=50, verbose_name='N° Cupón/Ticket')),
                ('cuotas', models.PositiveIntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_operacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_acreditacion_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente de Presentación'), ('PR', 'Presentado (Cierre Lote)'), ('AC', 'Acreditado / Liquidado'), ('RE', 'Rechazado / Contracargo')], default='PE', max_length=2)),
                ('liquidacion_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_liquidados', to='finanzas.movimientofondo')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='movimientofondo',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cupontarjeta', verbose_name='Cupón Tarjeta'),
        ),
    ]
