# Generated by Django 5.2.7 on 2026-02-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_remove_cupontarjeta_liquidacion_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantarjeta',
            name='coeficiente',
        ),
        migrations.RemoveField(
            model_name='plantarjeta',
            name='cuotas',
        ),
        migrations.RemoveField(
            model_name='plantarjeta',
            name='tna',
        ),
        migrations.AlterField(
            model_name='plantarjeta',
            name='nombre',
            field=models.CharField(help_text='Ej: Ahora 3, Visa Galicia', max_length=100),
        ),
        migrations.CreateModel(
            name='PlanCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuotas', models.PositiveIntegerField()),
                ('coeficiente', models.DecimalField(decimal_places=4, default=1.0, help_text='Coeficiente multiplicador (Ej: 1.20 para 20% interés)', max_digits=6)),
                ('tna', models.DecimalField(decimal_places=2, default=0, help_text='Costo financiero implícito', max_digits=6, verbose_name='TNA %')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_detalle', to='finanzas.plantarjeta')),
            ],
            options={
                'ordering': ['cuotas'],
                'unique_together': {('plan', 'cuotas')},
            },
        ),
    ]
