# Generated by Django 5.2.7 on 2026-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_remove_plantarjeta_coeficiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentafondo',
            name='tipo',
            field=models.CharField(choices=[('EF', 'Caja / Efectivo'), ('BA', 'Cuenta Bancaria'), ('VI', 'Billetera Virtual'), ('RE', 'Cuenta Recaudadora (Tarjetas)')], default='EF', max_length=2),
        ),
        migrations.AlterField(
            model_name='cupontarjeta',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente de Presentación'), ('PR', 'Presentado (Cierre Lote)'), ('LI', 'Liquidado / En Banco'), ('AC', 'Acreditado / Finalizado'), ('RE', 'Rechazado / Contracargo')], default='PE', max_length=2),
        ),
    ]
